export type Video = {
  id: string;
  title: string;
  channel: string;
  views: string;
  uploaded: string;
  duration: string;
  thumbnail: string;
};

export const videos: Video[] = [
  {
    id: "react-beginners",
    title: "React Tutorial for Beginners",
    channel: "Code Academy",
    views: "890K views",
    uploaded: "6 months ago",
    duration: "22:45",
    thumbnail: "https://i.ytimg.com/vi/bMknfKXIFA8/hqdefault.jpg",
  },
  {
    id: "js-crash-course",
    title: "JavaScript Crash Course",
    channel: "Programming With Mosh",
    views: "2.1M views",
    uploaded: "1 year ago",
    duration: "1:12:00",
    thumbnail: "https://i.ytimg.com/vi/W6NZfCO5SIk/hqdefault.jpg",
  },
  {
    id: "space-documentary",
    title: "Journey Through The Universe",
    channel: "Cosmic Docs",
    views: "640K views",
    uploaded: "5 months ago",
    duration: "18:34",
    thumbnail: "https://i.ytimg.com/vi/1w8Z0UOXVaY/hqdefault.jpg",
  },
  {
    id: "ai-future",
    title: "The Future of AI Explained",
    channel: "Tech Vision",
    views: "950K views",
    uploaded: "2 months ago",
    duration: "14:11",
    thumbnail: "https://i.ytimg.com/vi/2ePf9rue1Ao/hqdefault.jpg",
  },
  {
    id: "coding-music",
    title: "Coding Music Mix",
    channel: "Dev Beats",
    views: "320K views",
    uploaded: "4 weeks ago",
    duration: "45:00",
    thumbnail: "https://i.ytimg.com/vi/hHW1oY26kxQ/hqdefault.jpg",
  },
  {
    id: "basketball-highlights",
    title: "NBA Best Highlights 2025",
    channel: "Sports Arena",
    views: "1.5M views",
    uploaded: "1 month ago",
    duration: "9:45",
    thumbnail: "https://i.ytimg.com/vi/L_jWHffIx5E/hqdefault.jpg",
  },
  {
  id: "react-hooks",
  title: "React Hooks Explained in 10 Minutes",
  channel: "Dev Simplified",
  views: "780K views",
  uploaded: "8 months ago",
  duration: "10:12",
  thumbnail: "https://i.ytimg.com/vi/f687hBjwFcM/hqdefault.jpg",
},
{
  id: "ts-beginners",
  title: "TypeScript Tutorial for Beginners",
  channel: "Programming with Mosh",
  views: "1.1M views",
  uploaded: "1 year ago",
  duration: "32:55",
  thumbnail: "https://i.ytimg.com/vi/BwuLxPH8IDs/hqdefault.jpg",
},
{
  id: "css-flexbox",
  title: "CSS Flexbox in 20 Minutes",
  channel: "Web Dev Simplified",
  views: "520K views",
  uploaded: "7 months ago",
  duration: "20:03",
  thumbnail: "https://i.ytimg.com/vi/fYq5PXgSsbE/hqdefault.jpg",
},
{
  id: "html-crash",
  title: "HTML Crash Course",
  channel: "Traversy Media",
  views: "2.2M views",
  uploaded: "2 years ago",
  duration: "1:02:15",
  thumbnail: "https://i.ytimg.com/vi/UB1O30fR-EE/hqdefault.jpg",
},
{
  id: "react-project",
  title: "Build a React App From Scratch",
  channel: "Codevolution",
  views: "340K views",
  uploaded: "4 months ago",
  duration: "41:12",
  thumbnail: "https://i.ytimg.com/vi/w7ejDZ8SWv8/hqdefault.jpg",
},
{
  id: "python-ai",
  title: "Python AI Project Tutorial",
  channel: "Tech With Tim",
  views: "620K views",
  uploaded: "6 months ago",
  duration: "35:44",
  thumbnail: "https://i.ytimg.com/vi/JMUxmLyrhSk/hqdefault.jpg",
},
{
  id: "node-api",
  title: "Node.js REST API Tutorial",
  channel: "Academind",
  views: "890K views",
  uploaded: "1 year ago",
  duration: "28:20",
  thumbnail: "https://i.ytimg.com/vi/pKd0Rpw7O48/hqdefault.jpg",
},
{
  id: "tailwind",
  title: "Tailwind CSS Crash Course",
  channel: "Net Ninja",
  views: "480K views",
  uploaded: "10 months ago",
  duration: "25:11",
  thumbnail: "https://i.ytimg.com/vi/dFgzHOX84xQ/hqdefault.jpg",
},
{
  id: "figma-design",
  title: "Figma UI Design Tutorial",
  channel: "DesignCourse",
  views: "710K views",
  uploaded: "9 months ago",
  duration: "18:56",
  thumbnail: "https://i.ytimg.com/vi/FTFaQWZBqQ8/hqdefault.jpg",
},
{
  id: "ai-tools",
  title: "Top AI Tools for Developers",
  channel: "TechWorld",
  views: "560K views",
  uploaded: "2 months ago",
  duration: "11:40",
  thumbnail: "https://i.ytimg.com/vi/2ePf9rue1Ao/hqdefault.jpg",
},
{
  id: "react-router",
  title: "React Router Complete Guide",
  channel: "Code with Harry",
  views: "300K views",
  uploaded: "6 months ago",
  duration: "29:13",
  thumbnail: "https://i.ytimg.com/vi/59IXY5IDrBA/hqdefault.jpg",
},
{
  id: "docker-beginners",
  title: "Docker Tutorial for Beginners",
  channel: "Tech Primers",
  views: "670K views",
  uploaded: "1 year ago",
  duration: "40:21",
  thumbnail: "https://i.ytimg.com/vi/fqMOX6JJhGo/hqdefault.jpg",
},
{
  id: "linux-basics",
  title: "Linux Command Line Basics",
  channel: "freeCodeCamp",
  views: "1.3M views",
  uploaded: "2 years ago",
  duration: "55:30",
  thumbnail: "https://i.ytimg.com/vi/ZtqBQ68cfJc/hqdefault.jpg",
},
{
  id: "github-guide",
  title: "Git & GitHub Beginner Guide",
  channel: "Traversy Media",
  views: "1.8M views",
  uploaded: "2 years ago",
  duration: "37:22",
  thumbnail: "https://i.ytimg.com/vi/SWYqp7iY_Tc/hqdefault.jpg",
},
{
  id: "algorithm-basics",
  title: "Algorithms Explained Simply",
  channel: "CS Dojo",
  views: "950K views",
  uploaded: "1 year ago",
  duration: "15:05",
  thumbnail: "https://i.ytimg.com/vi/8hly31xKli0/hqdefault.jpg",
},
{
  id: "database-sql",
  title: "SQL Database Tutorial",
  channel: "ProgrammingKnowledge",
  views: "720K views",
  uploaded: "1 year ago",
  duration: "44:18",
  thumbnail: "https://i.ytimg.com/vi/HXV3zeQKqGY/hqdefault.jpg",
},
{
  id: "cybersecurity",
  title: "Cybersecurity Basics",
  channel: "NetworkChuck",
  views: "600K views",
  uploaded: "5 months ago",
  duration: "19:22",
  thumbnail: "https://i.ytimg.com/vi/inWWhr5tnEA/hqdefault.jpg",
},
{
  id: "ai-programming",
  title: "Machine Learning for Beginners",
  channel: "Simplilearn",
  views: "840K views",
  uploaded: "9 months ago",
  duration: "30:10",
  thumbnail: "https://i.ytimg.com/vi/GwIo3gDZCVQ/hqdefault.jpg",
},
{
  id: "javascript-advanced",
  title: "Advanced JavaScript Concepts",
  channel: "Academind",
  views: "540K views",
  uploaded: "7 months ago",
  duration: "27:50",
  thumbnail: "https://i.ytimg.com/vi/NCwa_xi0Uuc/hqdefault.jpg",
},
{
  id: "react-performance",
  title: "React Performance Optimization",
  channel: "Ben Awad",
  views: "420K views",
  uploaded: "8 months ago",
  duration: "16:44",
  thumbnail: "https://i.ytimg.com/vi/Tn6-PIqc4UM/hqdefault.jpg",
}
];